[package]
name = "tsicket_db"
version = "0.1.0"
authors = ["zhou <fliingelephant@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# diesel = { version = "1.0.0", features = ["mysql"] }    # ORM
