name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: build vue
        run: |
          cd admin_frontend 
          npm install
          npm run server
          cd ..


