name: CI
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          cd admin_frontend 
          npm install
          npm run build
          cd ..
      - name: check
        run: |
          cd backend
          cargo check --verbose --all
          cd ..


