name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build vue
        run: |
          cd admin_frontend
          npm set registry https://registry.npm.taobao.org
          npm install --progress=false
          npm run build

